    - name: Debug Kivy build manually
      if: steps.build_attempt.outcome == 'failure'
      shell: bash
      env:
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        PATH: /usr/bin:/home/runner/.local/bin:/home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:/home/runner/.buildozer/android/platform/android-sdk/platform-tools:${PATH}
      run: |
        echo "==== Searching for Kivy setup.py ===="
        WORKSPACE=$(pwd)
        KIVY_SETUP=$(find "$WORKSPACE/.buildozer/android/platform/build-"*/build/other_builds/kivy -name "setup.py" -type f 2>/dev/null | head -n1)
        HOSTPYTHON=$(find "$WORKSPACE/.buildozer/android/platform/build-"*/build/other_builds/hostpython3 -name "python3" -type f -executable 2>/dev/null | head -n1)
        
        echo "Kivy setup.py: $KIVY_SETUP"
        echo "Hostpython: $HOSTPYTHON"
        
        if [ -f "$KIVY_SETUP" ] && [ -f "$HOSTPYTHON" ]; then
          KIVY_DIR=$(dirname "$KIVY_SETUP")
          echo "Found Kivy dir: $KIVY_DIR"
          
          echo "==== Installing setuptools into hostpython ===="
          "$HOSTPYTHON" -m ensurepip || true
          "$HOSTPYTHON" -m pip install --upgrade pip setuptools wheel || true
          
          echo "==== Verifying setuptools ===="
          "$HOSTPYTHON" -c "import setuptools; print('setuptools version:', setuptools.__version__)"
          
          cd "$KIVY_DIR"
          
          echo "==== Running setup.py build_ext manually with full env ===="
          export NDKPLATFORM='NOTNONE'
          export USE_SDL2='1'
          export KIVY_SPLIT_EXAMPLES='1'
          
          set +e
          "$HOSTPYTHON" setup.py build_ext -v 2>&1 | tee /tmp/kivy_manual_build.log
          BUILD_STATUS=$?
          set -e
          
          echo "==== Manual build exit code: $BUILD_STATUS ===="
          if [ $BUILD_STATUS -eq 0 ]; then
            echo "SUCCESS! Kivy built successfully. The issue was missing setuptools in hostpython."
            echo "Now we need to fix the main build process to install setuptools before Kivy build."
          else
            echo "==== Manual build output (last 300 lines) ===="
            tail -n 300 /tmp/kivy_manual_build.log
          fi
        else
          echo "ERROR: Could not find Kivy setup.py or hostpython"
        fi
        
        exit 1
