name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libgles2-mesa-dev \
          libegl1-mesa-dev \
          cmake \
          ninja-build \
          libtool \
          automake \
          autoconf \
          pkg-config \
          libffi-dev \
          libssl-dev \
          openjdk-17-jdk
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade buildozer cython==0.29.36 virtualenv
    
    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
    
    - name: Cache Buildozer build directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: buildozer-build-${{ hashFiles('buildozer.spec') }}-${{ hashFiles('requirements.txt') }}
    
    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "platforms;android-31" "ndk;25.2.9519653"
    
    - name: Build with Buildozer
      run: |
        buildozer android debug
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TwitchDropsMiner-debug
        path: bin/*.apk
        retention-days: 30
    
    - name: Show build logs on failure
      if: failure()
      run: |
        echo "=== Buildozer log ==="
        cat .buildozer/android/platform/build-*/build.log || echo "No build.log found"
        echo "=== P4A log ==="
        find .buildozer -name "*.log" -exec echo "File: {}" \; -exec cat {} \;
