name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 1) GIT MUSÍ BYŤ NAINŠTALOVANÝ EŠTE PRED BUILDOZEROM
    - name: Ensure Git is installed
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        git --version

    # 2) ZÁKLADNÉ BALÍKY (bez gitu, už je vyššie)
    - name: Install system dependencies
      run: |
        sudo apt-get install -y python3-pip build-essential ffmpeg \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
          zlib1g-dev libgstreamer1.0 gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good openjdk-17-jdk unzip zip curl

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    # 3) LOKÁLNY ANDROID SDK PRE BUILDOZER
    - name: Prepare local Android SDK for Buildozer
      shell: bash
      run: |
        set -e
        export LOCAL_SDK="${HOME}/.buildozer/android/platform/android-sdk"
        mkdir -p "${LOCAL_SDK}/cmdline-tools/latest"
        if [ ! -x "${LOCAL_SDK}/cmdline-tools/latest/bin/sdkmanager" ]; then
          echo "Downloading Android cmdline-tools into Buildozer local SDK..."
          cd /tmp
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o clt.zip
          unzip -q clt.zip
          mv cmdline-tools/* "${LOCAL_SDK}/cmdline-tools/latest"/
        fi

        export ANDROID_SDK_ROOT="${LOCAL_SDK}"
        export ANDROID_HOME="${LOCAL_SDK}"

        echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH

        yes | "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --licenses || true
        "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" \
          "platform-tools" \
          "build-tools;36.1.0" \
          "platforms;android-33"

    - name: Cache Buildozer
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    # 4) BUILD
    - name: Build APK
      env:
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        PATH: /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:/home/runner/.buildozer/android/platform/android-sdk/platform-tools:${PATH}
      run: |
        # pre istotu ešte raz over git
        git --version
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TwitchDropsMiner-debug
        path: bin/*.apk
